### PR TITLE
v0.7.8

### PR DESCRIPTION
**Pull request by AlBlanc**
First "official" release since the fork:
 - [Migrate to AndroidX](https://github.com/ShamylZakariya/StickyHeaders/issues/96)
 - [Fix crash when using `notifySectionItemRangeRemoved` on last section item](https://github.com/ShamylZakariya/StickyHeaders/issues/82)
 - Update gradle and all depedencies  
 - Move package to "io.sportner.stickyheaders"

### CODE REVIEW

**Comment by ShamylZakariya** [comment]
Good work, @AlBlanc - sorry I've been MIA.

**Comment by ShamylZakariya** [comment]
I was having some issues with the maven distribution, but I think they're resolved now. I'm releasing `0.7.10` presently, which mainly fixes the maven distribution. For what it's worth, I look forward to maintaining this repo again. I missed android development!

**Comment by AlBlanc** [comment]
Great news, I would love to help.

Btw, you should steal my update for AndroidX ;) -> https://github.com/Sportner/StickyHeaders/commit/bb6580bbe2b2d559bd0eadd88fbe87fa7525ff60

**Comment by AlBlanc** [comment]
Nvm, I just saw a commit in your master that does the same job ;)

**Pull request closed without merging**
